version: '3'

services:
  bot:
    container_name: bot
    build:
      context: .
    stdin_open: true
    tty: true
    environment:
      - HUBOT_NAME=octobot
      - OCTOPRINT_URL=192.168.2.100
      - OCTOPRINT_PROTOCOL=http://
      - OCTOPRINT_PORT=8080
    env_file:
        - .env
    volumes:
      - ./images:/service/images
