version: '3'

services:
  bot:
    container_name: bot
    build:
      context: .
    stdin_open: true
    tty: true
    environment:
      - HUBOT_NAME=octobot
    env_file:
        - .env
    volumes:
      - ./images:/service/images
